### ISSUE TITLE
Markdown container does not support system dark theme

### ISSUE THREAD

**Issue by MairwunNx** [jeziellago/compose-markdown#2]
Dark theme can't be applied to markdown container and markdown child elements such as labels, code, table, etc.

Even when I've force turn on the dark theme it's does not produce any effects.

**Comment by jeziellago** [comment]
Hi @MairwunNx 
Check the latest version.

**Comment by jk2pr** [comment]
I'm not certain, but for me, the text colour remains the same in both dark and light modes, even though it should adjust automatically.

**Comment by jk2pr** [comment]
Did you get any solutions? It's not working for me, and the color remains the same even when I switch to dark mode.

**Comment by jk2pr** [comment]
After modifying background and text style, it is working.

 `MarkdownText(
        markdown = readmeText.orEmpty(),
        modifier = Modifier.background(MaterialTheme.colorScheme.background),
        style = LocalTextStyle.current.copy(color = LocalContentColor.current)
    )`

**Comment by jacobmattsson** [comment]
Dark mode still seem to be broken in 0.5.7. That makes this library useless for me ... 

With this simple `MarkdownText` composable:

```
MarkdownText(
    markdown = "Test of a **bold** label", 
    style = LocalTypography.current.body
)
```

, the text is rendered in black color in both Light and Dark mode, even though I have defined in my text style that the text color should be white for Dark mode:

I know that the text color can be (explicitly) specified, like this:

`style = TextStyle(color = Color.Blue)`

, but I want the text color to follow the theme.

If I use a regular `Text` composable: 

```
Text(
    "Test of a label with correct color in Dark and Light mode",
    style = LocalSamTypography.current.body
)
```

, the correct text colors are used for both Dark and Light mode.

This issue was closed back in 2021 with a comment to check the latest version. But it seems like I'm not the only one to still experience these problems after that.
